format = """
$os\
$username\
$directory\
$docker_context\
$python\
$golang\
$rust\
$cpp\
$c\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

right_format = """
[î‚¶](vesper)\
$battery\
[î‚´ ](color_pink)\
"""

palette = 'welp'
[palettes.welp]
color_fg0 = '#e5e1e7'
color_bg3 = '#665c54'
color_blue = '#00CCFF'
color_nblue = '#1BFFFF'
color_sblue = '#4682B4'
color_green = '#39FF14'
color_lgreen = '#BFFF00'
color_orange = '#FF6C00'
color_red = '#FF073A'
color_yellow = '#FFFF33'
color_pink = '#FF4DA6'
color_purple = '#E100FF'
color_black = '#000000'
color_brown = '#A3384A'
color_rust = '#B7410E'
vesper = '#FFC799'
vesper_alt = '#FFB86C'

[os]
disabled = false
style = 'fg:color_orange'

[os.symbols]
Arch = 'ïŒŒ'
# Arch = 'ó°£‡'
NixOS = 'î¡ƒ'

[username]
show_always = true
style_user = 'fg:color_orange'
style_root = 'fg:color_red'
format = '[ $user ]($style)'

[directory]
style = 'fg:color_yellow'
format = '[ $path ]($style)[$read_only]($style)'
truncation_length = 3
truncation_symbol = 'â€¦/'
home_symbol = 'ï€• '
read_only = 'ï€£'

[directory.substitutions]
'Documents' = 'ó°ˆ™ '
'Downloads' = 'ï€™ '
'Music' = 'ó°š '
'Pictures' = 'ï€¾ '
'Video' = 'ó±œ '
'Coding' = 'ï„¡ '
'Shared' = 'ï” '
'Public' = 'î·Š '

[git_branch]
symbol = 'îœ¥'
style = 'color_blue'
format = '[ $symbol $branch]($style)'

[git_status]
style = 'vesper_alt'
format = '[ $all_status]($style) [$ahead_behind$stashed](color_green)'
conflicted = '='  
untracked = '!'  
modified  = 'ï„ '  
renamed   = 'Â»'  
staged    = '+'  
deleted   = 'ï‡¸ '  
stashed   = 'â‰¡'
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = 'color_pink'

[c]
symbol = 'î˜ '
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_sblue)]($style)'

[cpp]
symbol = 'î˜ '
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = 'ğŸ¦€'
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_rust)]($style)'

[golang]
symbol = 'î˜§'
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_nblue)]($style)'

[python]
symbol = 'î˜†'
format = '[[ $symbol( $virtualenv) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = 'ïŒˆ'
style = 'bg:color_bg3'
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_blue)]($style)'

[cmd_duration]
format = '[ $duration]($style)'
style = 'color_green'

[character]
success_symbol = '[â¯](color_nblue)'
error_symbol = '[â¯](color_red)'
vimcmd_symbol = '[â®](color_pink)'

[battery]
unknown_symbol = ' îº¡ '
full_symbol = 'ğŸ”‹'
charging_symbol = 'îº¡ '
discharging_symbol = 'ğŸ’€'

[[battery.display]]
threshold = 30
style = 'fg:color_red'

[[battery.display]]
threshold = 60
style = 'fg:color_sblue'

[[battery.display]]
threshold = 80
style = 'fg:color_lgreen'

[[battery.display]]
threshold = 100
style = 'fg:color_nblue'
